### ISSUE TITLE
TTS development plan for v.0.6.0

### ISSUE THREAD

**Issue by kan-bayashi** [espnet/espnet#1329]
Continue from #977 

## Action items

- [ ] VAE-based Tacotron2 (e.g. [GMVAE-Tacotron2](https://arxiv.org/pdf/1810.07217.pdf))
	- Tensorflow implementation (Thanks @rishikksh20)  
	  https://github.com/rishikksh20/gmvae_tacotron  
      https://github.com/rishikksh20/vae_tacotron2
- [x] Knowledge distillation for FastSpeech (#1287)
- [x] Integrate real-time neural vocoder ([Parallel WaveGAN](https://arxiv.org/pdf/1910.11480.pdf)) (#1333)
    - Now working on https://github.com/kan-bayashi/ParallelWaveGAN
- [ ] Add neural vocoder synthesis stage in the recipe
- [ ] [Dynamic convolution attention](https://arxiv.org/abs/1910.10288)
- [ ] Re-design frontend modules
- [ ] Re-design embedding inputs
- [ ] Add ASR evaluation for all of the recipes
- [ ] Add subjective evalution instruction
- [ ] Add objective measure (e.g. RMSE, CD)
- [ ] Introduce a subjective evalaution
- [ ] Add difficult sentences for the genration 

If you have any nice ideas, please discuss it here.

**Comment by r9y9** [comment]
https://arxiv.org/abs/1910.10288 This seems worth trying :) i.e., support for GMM attention and dynamic convolution attention (DCA).

**Comment by rishikksh20** [comment]
@kan-bayashi Check this : https://github.com/rishikksh20/gmvae_tacotron , For GMVAE, it's working as style transfer but I am not able to figure out which latent variable responsible to control prosody of the voice.

**Comment by kan-bayashi** [comment]
@r9y9 Thanks. It looks nice. I added to action items.

Hi @rishikksh20. This is great!
We should check your implementation.
I'm very curious about the results on the noisy dataset.
Do you have any samples?

**Comment by rishikksh20** [comment]
@kan-bayashi actually I am only tested on LJSpeech which is a kind of flat voice so hard to judge the performance of VAE but here are some samples: https://soundcloud.com/rishikesh-kumar-1/sets/vae_tacotron

**Comment by kan-bayashi** [comment]
@rishikksh20 Thanks for sharing samples!
Yes, even if without VAE, the model trained on ljspeech is good enough, I think.
To check the effectiveness of VAE, we should try multi-speaker setting e.g. LibriTTS.

**Comment by sw005320** [comment]
- I think it's better to add very detail instructions of the subjective evaluation (e.g., step-by-step instruction with the snapshot). ESPnet's concept is to do everything including evaluation within a recipe. We cannot automatically include this part, but we should provide detailed instructions.
- make ASR subjective evaluation default for all TTS recipes
- Is it possible to centralize our current existing models, sample audios, and demonstration pages? We should also include ASR, MT, etc.

**Comment by sw005320** [comment]
Also, we may have other objective evaluation measures, e.g., RMSE and CD when we have a ground truth sample. I know that this is not a good measure for TTS, but we could still discuss some aspects without subjective evaluation.

**Comment by kan-bayashi** [comment]
I finished Parallel WaveGAN implementation and made demo HP.
https://kan-bayashi.github.io/ParallelWaveGAN/
I think almost the same quality as the official samples.

**Comment by r9y9** [comment]
I think it's time to test our models with hard input sentences (e.g., out of domain texts, long and short inputs, etc) to evaluate robustness of each model.

As a first step, how about trying the hard sentences noted in the [FastSpeech paper](https://arxiv.org/abs/1905.09263)? It would be great to add this to the action items.

**Comment by WhiteFu** [comment]
@kan-bayashi   Good Job! But I have a small problem, I hope you can guide me.   I want to know how to select the FFT/Shift/Win parameters.  Why 2048/300/1200 for CSMSC instead of 1024/256/1024?   Is it determined by experimental results?

**Comment by kan-bayashi** [comment]
@WhiteFu For 24k Hz, we follow the setting in the original Tacotron 2 paper, as @r9y9 recommended #1192.

**Comment by WhiteFu** [comment]
@kan-bayashi  Thanks for your reply:)
