### ISSUE TITLE
Development plan for ESPnet2 sound event detection

### ISSUE THREAD

**Issue by m-koichi** [espnet/espnet#2336]
We are developing some functions for sound event detection in ESPnet2.
Sound event detection is somehow different from speech processing. However, some signal processing and machine learning techniques are common.
We are welcome to your comments and suggestions.
For now, we are planning to reproduce [this Conformer-based SED system](http://dcase.community/documents/challenge2020/technical_reports/DCASE2020_Miyazaki_108.pdf) using ESPnet2 functions.

# Progress & Plans
- [ ] Sound event detection recipe template
- [ ] Prepare pre-trained model 

# Networks
- [ ] CRNN
- [ ] Transformer ([Paper](https://arxiv.org/pdf/1706.03762.pdf))
- [ ] Conformer ([Paper](https://arxiv.org/pdf/2005.08100.pdf))

# Document
- [ ] Add documentation in `https://github.com/espnet/espnet/tree/master/doc`
- [ ] Describe some features and functions in the main `README.md`

# Recipe
- [ ] DCASE2020 Task4 ([Link](http://dcase.community/challenge2020/task-sound-event-detection-and-separation-in-domestic-environments))
- [ ] DESED ([Link](https://project.inria.fr/desed/))

# Others
- [ ] Evaluation measures
	- [ ] Segment-based macro F1 score, Event-based macro F1 score in [TUT-ARG/sed_eval](https://github.com/TUT-ARG/sed_eval) 
	- [ ] Polyphonic Sound Detection Score in [audioanalytic/psds_eval](https://github.com/audioanalytic/psds_eval)
- [ ] Post-processing functions
	- [ ] Thresholding
	- [ ] Median filtering
- [ ] Semi-supervised learning
	- [ ] Mean-teacher ([Paper](https://arxiv.org/abs/1703.01780))
- [ ] Data augmentation
	- [ ] Mixup ([Paper](https://arxiv.org/pdf/1710.09412.pdf))
	- [ ] Time-shifting
