### ISSUE TITLE
Top 20 slowest tests

### ISSUE THREAD

**Issue by ShigekiKarita** [espnet/espnet#2459]
I found running test is really slower now! 

- master: [30:45](https://app.circleci.com/jobs/github/espnet/espnet/20951)
- v 0.9.0: [10:38](https://app.circleci.com/pipelines/github/espnet/espnet/5617/workflows/d0068615-59ab-41f7-9291-59049c3e5186/jobs/18906)
- v 0.8.0: NA
- v 0.7.0: [13:45](https://app.circleci.com/pipelines/github/espnet/espnet/4748/workflows/01d7470c-ea49-4241-bb57-fc4198e76e24/jobs/15785)
- v 0.6.0: [5:09](https://app.circleci.com/pipelines/github/espnet/espnet/2768/workflows/9f28786d-0ee9-44be-854e-f618500e28aa/jobs/9100)

in CircleCI's ubuntu-18 image (running out of free credits!)

I think unit tests should be fast because test-driven dev requires that property (while the integration tests can be slow). Here are the top 20 slowest test files:

- [x] 0 ('test/test_beam_search.py', 536.879999999997) -> 1.91 (#2462)
- [x] 1 ('test/test_batch_beam_search.py', 289.2799999999999) -> 1.45 (#2462)
- [x] 2 ('test/test_e2e_asr_mulenc.py', 216.11999999999998) -> 8.86 (#2480)
- [x] 3 ('test/espnet2/enh/nets/test_beamformer_net.py', 212.21000000002525) -> 12.76s (#2489)
- [x] 4 ('test/espnet2/tts/test_transformer.py', 69.75999999999985) -> 5.30 (#2461)
- [x] 5 ('test/test_e2e_st_transformer.py', 49.809999999999995) -> 8.0 (#2464)
- [x] 6 ('test/test_asr_init.py', 42.18) -> 5.4 (#2444)
- [x] 7 ('test/test_e2e_asr_sa_transducer.py', 38.73000000000001) -> (#98dof55: 43.5) -> 5.89 (#2444)
- [x] 8 ('test/test_e2e_asr_transformer.py', 34.8) -> 5.0 (#2464)
- [x] 9 ('test/test_e2e_asr_conformer.py', 32.07) -> 5.0 (#2464)
- [x] 10 ('test/test_recog.py', 22.89) -> 5.18 (#2486)
- [x] 11 ('test/test_e2e_asr.py', 21.729999999999997) -> 9.79s (#2488)
- [x] 12 ('test/espnet2/tts/test_tacotron2.py', 18.9999999999998) -> 2.15 (#2461)
- [x] 13 ('test/espnet2/tts/test_fastspeech2.py', 17.110000000000078) -> 2.19 (#2461)
- [x] 14 ('test/espnet2/enh/nets/test_tasnet.py', 16.99999999999999) -> 7.01 (#2491)
- [x] 15 ('test/test_e2e_mt_transformer.py', 15.910000000000002) -> 5.0 (#2464)
- [x] 16 ('test/test_e2e_asr_maskctc.py', 12.639999999999999) -> 5.07 (#2493)
- [x] 17 ('test/espnet2/tts/test_fastspeech.py', 8.749999999999961) -> 3.10 (#2461)
- [ ] 18 ('test/espnet2/asr/decoder/test_transformer_decoder.py', 8.039999999999996)
- [ ] 19 ('test/espnet2/lm/test_seq_rnn_lm.py', 5.039999999999998)

top20 total 0:27:49.950000
(test python: total 30:45)

I summarized the benchmark per file because I like well-organized smaller test files, and easy to start PRs per files. Ideally, if we can run these tests within ~1 sec, unit tests only take 3m in total.

Appendix: script to calc top 20
```python
# wget https://circleci.com/api/v1.1/project/github/espnet/espnet/20951/output/105/0?file=true&allocation-id=5f5bdcac8763316b07dced1c-0-build%2F4AD5A548 -O0.txt
import datetime
import sys
import collections

d = collections.defaultdict(int)
begin = False
for line in open("0.txt", "r"):
    if not begin:
        if "slowest durations" in line:
            begin = True
        continue
    if begin:
        if line.strip() == "":
            break
    ls = line.split()
    d[ls[2].split("::")[0]] += float(ls[0][:-1])

total = 0
for i, l in enumerate(sorted(d.items(), key=lambda kv: -kv[1])[:20]):
    print(i, l)
    total += l[1]
print(datetime.timedelta(seconds=total))
```
[0.txt](https://github.com/espnet/espnet/files/5212342/0.txt)

## tips for faster testing

- replace file IOs with mock functions (file IO gets very slow sometimes in CI)
- replace `importlib` with real import statements
- use the smallest parameters (e.g., batch_size=2)
- remove unnecessary (i.e., no contribution to coverage) `pytest.parameterized` cases

**Comment by ShigekiKarita** [comment]
First, I will fix `test_beam_search.py` and `test_batch_beam_search.py` because I am the original author of them. If other authors can improve these tests, that would be great!

**Comment by kan-bayashi** [comment]
I will fix tts ones!

**Comment by ShigekiKarita** [comment]
I updated the top20 finding script because of bug to grep filenames

**Comment by b-flo** [comment]
I'll fix `test/test_e2e_asr_sa_transducer.py`. Should we also speed-up test outside top 20?

**Comment by ShigekiKarita** [comment]
Thanks! IMO, top 20 is enough because they took 90% of the total execution time but files consuming more than ~3 seconds might be annoying. Here is full listing of test execution time per files.
[test_time_full.txt](https://github.com/espnet/espnet/files/5212352/test_time_full.txt)

**Comment by ShigekiKarita** [comment]
FYI: I tried [pytest-parallel](https://pypi.org/project/pytest-parallel/) and it runs very fast in my laptop (12 cores). It was great for rapid local testing.
```
$ time CUDA_VISIBLE_DEVICES=NoDevFiles pytest -k "not transfer" ./test/*.py --workers auto
...
1048 passed, 1507 skipped, 50 deselected, 4 warnings in 100.75s (0:01:40)
1074.07s user 42.30s system 1115% cpu 1:40.09 total
```
but there are some problems in transfer learning tests because of multi processing conflicts related to file IO.

**Comment by sw005320** [comment]
> 3 ('test/espnet2/enh/nets/test_beamformer_net.py', 212.21000000002525)

@LiChenda, @Emrys365, @shincling, could you do it?

**Comment by Emrys365** [comment]
> > 3 ('test/espnet2/enh/nets/test_beamformer_net.py', 212.21000000002525)
> 
> @LiChenda, @Emrys365, @shincling, could you do it?

Yes, I will fix `test/espnet2/enh/nets/test_beamformer_net.py`.

**Comment by ShigekiKarita** [comment]
As v0.9.3 released, I recompute the ranking with log https://circleci.com/api/v1.1/project/github/espnet/espnet/21233/output/105/0?file=true&allocation-id=5f6042a0651d6e58c50e7234-0-build%2F144C8D1F
1. ('test/test_e2e_asr_mulenc.py', 167.85000000000008)
2. ('test/espnet2/enh/nets/test_beamformer_net.py', 163.1100000000071)
3. ('test/test_e2e_asr_sa_transducer.py', 29.64)
4. ('test/test_e2e_asr.py', 16.050000000000015)
5. ('test/espnet2/enh/nets/test_tasnet.py', 15.889999999999988)
6. ('test/test_recog.py', 15.64)
7. ('test/test_e2e_asr_maskctc.py', 11.0)
8. ('test/espnet2/tts/test_transformer.py', 6.339999999999998)
9. ('test/test_asr_init.py', 5.920000000000002)
10. ('test/espnet2/asr/decoder/test_transformer_decoder.py', 5.749999999999991)

total: 0:08:31.19

We’re almost there!

**Comment by ruizhilijhu** [comment]
I will fix the test/test_e2e_asr_mulenc.py !

**Comment by b-flo** [comment]
I'll also fix test/test_asr_init.py

**Comment by ruizhilijhu** [comment]
Plotting of attention and CTC consumed 80% run time in test/test_e2e_asr_mulenc.py.

For example: 
https://github.com/espnet/espnet/blob/8f725c7efb838840460d2414570fcf81adb8cf2d/test/test_e2e_asr_mulenc.py#L566
https://github.com/espnet/espnet/blob/8f725c7efb838840460d2414570fcf81adb8cf2d/test/test_e2e_asr_mulenc.py#L569
https://github.com/espnet/espnet/blob/8f725c7efb838840460d2414570fcf81adb8cf2d/test/test_e2e_asr_mulenc.py#L584


Any suggestions to deal with this?

**Comment by b-flo** [comment]
I had the same issue in `espnet/test/test_e2e_asr_sa_transducer.py`. I removed plotting from `test_model_trainable_and_decodable()` test and added another method to test attention computation and plotting.

**Comment by ruizhilijhu** [comment]
> I had the same issue in `espnet/test/test_e2e_asr_sa_transducer.py`. I removed plotting from `test_model_trainable_and_decodable(...)` and added another method to test attention computation and plotting for specific cases.

Thank you very much! This is very helpful.

**Comment by ShigekiKarita** [comment]
Thanks to your contributions, now `test_python.sh`[only took 6:21 in Circle CI ubuntu18](https://circleci.com/api/v1.1/project/github/espnet/espnet/21289/output/105/0?file=true&allocation-id=5f61e989ff854b4aa34dd069-0-build%2FCBBA88B). All test cases (not files) finished within ~1 sec except for 11 cases. 

To keep unit tests fast, I would like to introduce [pytest-timeouts](https://pypi.org/project/pytest-timeouts/). For example, `pytest --execution-timeout 2.0` raises time-out error when any cases exceed 2.0sec. Don't worry you can still exclude exceptional cases by `@pytest.mark.execution_timeout(5.0)`. Please let me know if you consider 2.0 sec timeout sounds bad (shorter or longer is better?).

**Comment by sw005320** [comment]
I think this is a good idea.
Shorter or longer than 2.0 sec could be adjusted experimentally later.

**Comment by LiChenda** [comment]
I'll fix ('test/espnet2/enh/nets/test_tasnet.py', 15.889999999999988)

**Comment by ShigekiKarita** [comment]
UPDATE: PR #2520 installed pytest-timeouts with the 2.0 sec execution time limit to keep unittests fast. Finally,  ci/test_python.sh only took **2:28**. I believe it cannot be faster anymore. https://app.circleci.com/pipelines/github/espnet/espnet/6465/workflows/99704a08-a675-49b2-a79b-62c306c7d98c/jobs/21806

Thanks for your huge contributions! I'm glad to close this issue :smile:
