### ISSUE TITLE
Development Plan for ESPNet2 -- Speaker Diarization

### ISSUE THREAD

**Issue by ftshijt** [espnet/espnet#3040]
We have been developing (enhancing) the ESPnet2 for the speaker diarization task. The [base code](https://github.com/espnet/espnet/pull/2939) follows the [EEND](https://github.com/hitachi-speech/EEND)

Welcome your requests for these particular directions and contributions! The followings are our development plans.

## Progress & Plan

- [x] A new task for speaker diarization
- [x] Speaker diarization recipe template
- [ ] Joint system with ASR
- [ ] Joint system with Enhancement/Separation

## Network Architectures:
- [x] Transformer/RNN/conformer
- [x] [decoder-encoder attractor](https://arxiv.org/abs/2005.09921)
- [ ] [speaker-wise chain rule](https://arxiv.org/abs/2006.01796)
- [ ] [RSAN](https://arxiv.org/abs/2003.03987) （joint-separation-diarization)
- [ ] [UIS-RNN](https://arxiv.org/abs/1810.04719) (joint-segmentation-clustering)

## Documentation 
- [ ] add documentation in https://github.com/espnet/espnet/tree/master/doc
- [ ] describe some features and functions in the main README.md
- [ ] prepare the webpage to put some demonstration
- [ ] create notebook for the demo

## Recipe:
- [x] mini_librispeech (toy data)
- [x] libri_mix
- [x] callhome
- [ ] ami
- [ ] dihard I
- [ ] dihard II
- [ ] dihard III
- [ ] voxconverse

## Others
- [ ] ASR as evaluation metric 
- [ ] More loss functions
- [ ] integration test
- [x] unit test
- [ ] flexibly changing of the base network architecture, e.g., BLSTM <-> CNN <-> Confromer

**Comment by sw005320** [comment]
Thanks, @ftshijt for summarizing the status!
If someone is interested in contributing to this project, please feel free to contact us.
Also, we welcome any requests about this speaker diarization topics!

**Comment by Alex-Songs** [comment]
cool

**Comment by ftshijt** [comment]
@YushiUeda Hi, probably you could also update the status based on your implementation

**Comment by YushiUeda** [comment]
@ftshijt Thanks for the suggestion! I will update the status.

**Comment by nellorebhanuteja** [comment]
Is this task active ?

**Comment by ftshijt** [comment]
@nellorebhanuteja  thanks for your following-up. We are still active in terms of diarization. Our latest goal is to publish the diarization+enhancement implementation boosted in https://github.com/espnet/espnet/pull/4339 by @YushiUeda

**Comment by ftshijt** [comment]
@nellorebhanuteja  thanks for your following-up. We are still active in terms of diarization. Our latest goal is to publish the diarization+enhancement implementation boosted in https://github.com/espnet/espnet/pull/4339 by @YushiUeda
