### ISSUE TITLE
Upgrade pytorch version to 1.9.0 and drop old ones (< 1.3)

### ISSUE THREAD

**Issue by ShigekiKarita** [espnet/espnet#3300]
Now we support too many pytorch versions 1.0.1 - 1.8.1. I think it is high time to drop old ones when we support new one, 1.9.0. I would like to discuss which versions to remove. 

At this moment, I and @sw005320 consider dynamic quantization (#3210) is an impactful feature. To make it enabled by default, we should drop the incompatible versions < 1.3. https://github.com/pytorch/pytorch/releases/tag/v1.3.0

TODO: volunteers are welcomed
- [x] update CI to add 1.9.0 and drop ver < 1.3 (#3299)
- [x] clean up espnet1 code dispatching old pytorch < 1.3.0 (#3301)
- [x] clean up espnet2 code dispatching old pytorch < 1.3.0 (#3303)
- [x] major update espnet to **v0.10.0**

```
$ cd espnet; grep -r version
lm/chainer_backend/lm.py:    # display chainer version
lm/chainer_backend/lm.py:    logging.info("chainer version = " + chainer.__version__)
lm/lm_utils.py:        # Floating point version of epoch.
lm/lm_utils.py:            # guess previous_epoch_detail for older version
lm/pytorch_backend/lm.py:    # display torch version
lm/pytorch_backend/lm.py:    logging.info("torch version = " + torch.__version__)
asr/chainer_backend/asr.py:    # display chainer version
asr/chainer_backend/asr.py:    logging.info("chainer version = " + chainer.__version__)
asr/chainer_backend/asr.py:    # display chainer version
asr/chainer_backend/asr.py:    logging.info("chainer version = " + chainer.__version__)
asr/pytorch_backend/asr.py:if sys.version_info[0] == 2:
asr/pytorch_backend/recog.py:        # NOTE: for a compatibility with less than 0.5.0 version models
vc/pytorch_backend/vc.py:        # perform padding and conversion to tensor
tts/pytorch_backend/tts.py:        # perform padding and conversion to tensor
st/pytorch_backend/st.py:if sys.version_info[0] == 2:
nets/pytorch_backend/rnn/decoders.py:from distutils.version import LooseVersion
nets/pytorch_backend/rnn/decoders.py:        if LooseVersion(torch.__version__) < LooseVersion("1.0"):
nets/pytorch_backend/rnn/attentions.py:    This attention is an extended version of location aware attention.
nets/pytorch_backend/rnn/attentions.py:    This attention is an extended version of location aware attention.
nets/pytorch_backend/lm/default.py:        # NOTE: for a compatibility with less than 0.5.0 version models
nets/pytorch_backend/lm/default.py:        # NOTE: for a compatibility with less than 0.6.1 version models
nets/pytorch_backend/lm/default.py:        # NOTE: for a compatibility with less than 0.9.7 version models
nets/pytorch_backend/lm/default.py:        # NOTE: for a compatibility with less than 0.9.7 version models
nets/pytorch_backend/lm/transformer.py:        # NOTE: for a compatibility with less than 0.9.7 version models
nets/pytorch_backend/lm/transformer.py:        # NOTE: for a compatibility with less than 0.9.7 version models
nets/pytorch_backend/lm/transformer.py:        # NOTE: for a compatibility with less than 0.9.7 version models
nets/pytorch_backend/transformer/attention.py:    """Multi-Head Attention layer with relative position encoding (old version).
nets/pytorch_backend/transformer/mask.py:from distutils.version import LooseVersion
nets/pytorch_backend/transformer/mask.py:is_torch_1_2_plus = LooseVersion(torch.__version__) >= LooseVersion("1.2.0")
nets/pytorch_backend/transformer/mask.py:# LooseVersion('1.2.0') == LooseVersion(torch.__version__) can't include e.g. 1.2.0+aaa
nets/pytorch_backend/transformer/mask.py:    LooseVersion("1.3") > LooseVersion(torch.__version__) >= LooseVersion("1.2")
nets/pytorch_backend/transformer/embedding.py:    """Relative positional encoding module (old version).
nets/pytorch_backend/tacotron2/decoder.py:    The Prenet preforms nonlinear conversion
nets/pytorch_backend/frontends/dnn_beamformer.py:from distutils.version import LooseVersion
nets/pytorch_backend/frontends/dnn_beamformer.py:is_torch_1_2_plus = LooseVersion(torch.__version__) >= LooseVersion("1.2.0")
nets/pytorch_backend/frontends/dnn_beamformer.py:is_torch_1_3_plus = LooseVersion(torch.__version__) >= LooseVersion("1.3.0")
nets/pytorch_backend/transducer/tdnn.py:        """Create outputs with subsampled version of pos_emb and masks.
nets/pytorch_backend/transducer/vgg2l.py:        """Create a subsampled version of x_mask.
nets/pytorch_backend/fastspeech/length_regulator.py:from distutils.version import LooseVersion
nets/pytorch_backend/fastspeech/length_regulator.py:is_torch_1_1_plus = LooseVersion(torch.__version__) >= LooseVersion("1.1")
nets/pytorch_backend/ctc.py:from distutils.version import LooseVersion
nets/pytorch_backend/ctc.py:            if LooseVersion(torch.__version__) < LooseVersion("1.7.0")
nets/pytorch_backend/ctc.py:            LooseVersion(torch.__version__) < LooseVersion("1.1.0")
nets/pytorch_backend/ctc.py:            logging.warning(f"CTC was set to {self.ctc_type} due to PyTorch version.")
nets/pytorch_backend/e2e_vc_transformer.py:    Voice Conversion Using Transformer with
nets/pytorch_backend/e2e_vc_transformer.py:        Voice Conversion Using Transformer with
nets/ctc_prefix_score.py:        # Base indices for index conversion
mt/pytorch_backend/mt.py:if sys.version_info[0] == 2:
utils/training/iterators.py:        if int(chainer._version.__version__[0]) <= 4:
utils/training/iterators.py:        if int(chainer._version.__version__[0]) <= 4:
bin/lm_train.py:from espnet import __version__
bin/lm_train.py:    # add version info in args
bin/lm_train.py:    args.version = __version__
bin/asr_train.py:from distutils.version import LooseVersion
bin/asr_train.py:from espnet import __version__
bin/asr_train.py:is_torch_1_2_plus = LooseVersion(torch.__version__) >= LooseVersion("1.2")
bin/asr_train.py:    # add version info in args
bin/asr_train.py:    args.version = __version__
bin/st_train.py:from distutils.version import LooseVersion
bin/st_train.py:from espnet import __version__
bin/st_train.py:is_torch_1_2_plus = LooseVersion(torch.__version__) >= LooseVersion("1.2")
bin/st_train.py:    # add version info in args
bin/st_train.py:    args.version = __version__
bin/tts_train.py:from espnet import __version__
bin/tts_train.py:    # add version info in args
bin/tts_train.py:    args.version = __version__
bin/vc_decode.py:        if platform.python_version_tuple()[0] == "2":
bin/mt_train.py:from distutils.version import LooseVersion
bin/mt_train.py:from espnet import __version__
bin/mt_train.py:is_torch_1_2_plus = LooseVersion(torch.__version__) >= LooseVersion("1.2")
bin/mt_train.py:    # add version info in args
bin/mt_train.py:    args.version = __version__
bin/vc_train.py:"""Voice conversion model training script."""
bin/vc_train.py:from espnet import __version__
bin/vc_train.py:        description="Train a new voice conversion (VC) model on one CPU, "
bin/vc_train.py:    # add version info in args
bin/vc_train.py:    args.version = __version__
bin/tts_decode.py:        if platform.python_version_tuple()[0] == "2":
__init__.py:version_file = os.path.join(dirname, "version.txt")
__init__.py:with open(version_file, "r") as f:
__init__.py:    __version__ = f.read().strip()
transform/transformation.py:PY2 = sys.version_info[0] == 2
```
```
$ cd espnet2; grep -r version
fileio/rttm.py:        This is an extend version of standard RTTM format for espnet.
diar/espnet_model.py:from distutils.version import LooseVersion
diar/espnet_model.py:if LooseVersion(torch.__version__) >= LooseVersion("1.6.0"):
schedulers/noam_lr.py:from distutils.version import LooseVersion
schedulers/noam_lr.py:     thus the behaviour isn't guaranteed at forward PyTorch version.
schedulers/noam_lr.py:        if LooseVersion(torch.__version__) < LooseVersion("1.1.0"):
schedulers/noam_lr.py:            raise NotImplementedError(f"Require PyTorch>=1.1.0: {torch.__version__}")
schedulers/warmup_lr.py:from distutils.version import LooseVersion
schedulers/warmup_lr.py:        if LooseVersion(torch.__version__) < LooseVersion("1.1.0"):
schedulers/warmup_lr.py:            raise NotImplementedError(f"Require PyTorch>=1.1.0: {torch.__version__}")
schedulers/abs_scheduler.py:from distutils.version import LooseVersion
schedulers/abs_scheduler.py:if LooseVersion(torch.__version__) >= LooseVersion("1.3.0"):
asr/frontend/default.py:        # 1. Domain-conversion: e.g. Stft: time -> time-freq
asr/specaug/specaug.py:from distutils.version import LooseVersion
asr/specaug/specaug.py:if LooseVersion(torch.__version__) >= LooseVersion("1.1"):
asr/espnet_model.py:from distutils.version import LooseVersion
asr/espnet_model.py:if LooseVersion(torch.__version__) >= LooseVersion("1.6.0"):
main_funcs/pack_funcs.py:        python=sys.version,
main_funcs/pack_funcs.py:        meta_objs.update(torch=torch.__version__)
main_funcs/pack_funcs.py:        meta_objs.update(espnet=espnet.__version__)
tts/feats_extract/log_mel_fbank.py:        # 1. Domain-conversion: e.g. Stft: time -> time-freq
tts/feats_extract/energy.py:        # Domain-conversion: e.g. Stft: time -> time-freq
tts/espnet_model.py:from distutils.version import LooseVersion
tts/espnet_model.py:if LooseVersion(torch.__version__) >= LooseVersion("1.6.0"):
enh/espnet_model.py:from distutils.version import LooseVersion
enh/espnet_model.py:is_torch_1_3_plus = LooseVersion(torch.__version__) >= LooseVersion("1.3.0")
enh/layers/dnn_beamformer.py:from distutils.version import LooseVersion
enh/layers/dnn_beamformer.py:is_torch_1_2_plus = LooseVersion(torch.__version__) >= LooseVersion("1.2.0")
enh/layers/dnn_beamformer.py:is_torch_1_3_plus = LooseVersion(torch.__version__) >= LooseVersion("1.3.0")
enh/layers/beamformer.py:from distutils.version import LooseVersion
enh/layers/beamformer.py:is_torch_1_1_plus = LooseVersion(torch.__version__) >= LooseVersion("1.1.0")
torch_utils/recursive_op.py:from distutils.version import LooseVersion
torch_utils/recursive_op.py:    if LooseVersion(torch.__version__) > LooseVersion("1.0.1"):
torch_utils/pytorch_version.py:def pytorch_cudnn_version() -> str:
torch_utils/pytorch_version.py:        f"pytorch.version={torch.__version__}, "
torch_utils/pytorch_version.py:            f"cudnn.version={torch.backends.cudnn.version()}, "
train/reporter.py:from distutils.version import LooseVersion
train/reporter.py:if LooseVersion(torch.__version__) >= LooseVersion("1.1.0"):
train/reporter.py:        if LooseVersion(torch.__version__) >= LooseVersion("1.4.0"):
train/trainer.py:from distutils.version import LooseVersion
train/trainer.py:if LooseVersion(torch.__version__) >= LooseVersion("1.1.0"):
train/trainer.py:    if LooseVersion(torch.__version__) > LooseVersion("1.0.1"):
train/trainer.py:if LooseVersion(torch.__version__) >= LooseVersion("1.6.0"):
train/trainer.py:            if LooseVersion(torch.__version__) < LooseVersion("1.6.0"):
train/iterable_dataset.py:from distutils.version import LooseVersion
train/iterable_dataset.py:if LooseVersion(torch.__version__) >= LooseVersion("1.2"):
utils/griffin_lim.py:from distutils.version import LooseVersion
utils/griffin_lim.py:    if LooseVersion(librosa.__version__) >= LooseVersion("0.7.0"):
utils/griffin_lim.py:        # use slower version of Grriffin-Lim algorithm
utils/griffin_lim.py:            "librosa version is old. use slow version of Grriffin-Lim algorithm."
utils/griffin_lim.py:    """Spectrogram to waveform conversion module."""
__init__.py:from espnet import __version__  # NOQA
layers/time_warp.py:from distutils.version import LooseVersion
layers/time_warp.py:if LooseVersion(torch.__version__) >= LooseVersion("1.1"):
layers/stft.py:from distutils.version import LooseVersion
layers/stft.py:        if LooseVersion(torch.__version__) >= LooseVersion("1.6.0"):
tasks/abs_task.py:from distutils.version import LooseVersion
tasks/abs_task.py:from espnet import __version__
tasks/abs_task.py:from espnet2.torch_utils.pytorch_version import pytorch_cudnn_version
tasks/abs_task.py:if LooseVersion(torch.__version__) >= LooseVersion("1.5.0"):
tasks/abs_task.py:if LooseVersion(torch.__version__) >= LooseVersion("1.2.0"):
tasks/abs_task.py:if LooseVersion(torch.__version__) >= LooseVersion("1.1.0"):
tasks/abs_task.py:if LooseVersion(torch.__version__) >= LooseVersion("1.3.0"):
tasks/abs_task.py:        args.version = __version__
tasks/abs_task.py:        logging.info(pytorch_cudnn_version())
tasks/abs_task.py:        if LooseVersion(torch.__version__) >= LooseVersion("1.2"):
```
```
$ cd test; grep -r version
test_e2e_asr_transducer.py:    if trans_type == "warp-rnnt" and torch.version.cuda != "10.0":
test_asr_quantize.py:torch = pytest.importorskip("torch", minversion="1.3.0")
espnet2/schedulers/test_noam_lr.py:from distutils.version import LooseVersion
espnet2/schedulers/test_noam_lr.py:    LooseVersion(torch.__version__) < LooseVersion("1.1.0"),
espnet2/schedulers/test_warmup_lr.py:from distutils.version import LooseVersion
espnet2/schedulers/test_warmup_lr.py:    LooseVersion(torch.__version__) < LooseVersion("1.1.0"),
espnet2/schedulers/test_warmup_lr.py:    LooseVersion(torch.__version__) < LooseVersion("1.1.0"),
espnet2/enh/separator/test_beamformer.py:from distutils.version import LooseVersion
espnet2/enh/separator/test_beamformer.py:is_torch_1_2_plus = LooseVersion(torch.__version__) >= LooseVersion("1.2.0")
espnet2/enh/encoder/test_stft_encoder.py:from distutils.version import LooseVersion
espnet2/enh/encoder/test_stft_encoder.py:is_torch_1_2_plus = LooseVersion(torch.__version__) >= LooseVersion("1.2.0")
espnet2/enh/decoder/test_stft_decoder.py:from distutils.version import LooseVersion
espnet2/enh/decoder/test_stft_decoder.py:is_torch_1_2_plus = LooseVersion(torch.__version__) >= LooseVersion("1.2.0")
espnet2/enh/layers/test_enh_layers.py:from distutils.version import LooseVersion
espnet2/enh/layers/test_enh_layers.py:is_torch_1_1_plus = LooseVersion(torch.__version__) >= LooseVersion("1.1.0")
espnet2/enh/test_espnet_model.py:from distutils.version import LooseVersion
espnet2/enh/test_espnet_model.py:is_torch_1_2_plus = LooseVersion(torch.__version__) >= LooseVersion("1.2.0")
espnet2/torch_utils/test_pytorch_version.py:from espnet2.torch_utils.pytorch_version import pytorch_cudnn_version
espnet2/torch_utils/test_pytorch_version.py:def test_pytorch_cudnn_version():
espnet2/torch_utils/test_pytorch_version.py:    print(pytorch_cudnn_version())
espnet2/train/test_reporter.py:from distutils.version import LooseVersion
espnet2/train/test_reporter.py:if LooseVersion(torch.__version__) >= LooseVersion("1.1.0"):
espnet2/train/test_iterable_dataset.py:from distutils.version import LooseVersion
espnet2/train/test_iterable_dataset.py:    LooseVersion(torch.__version__) < LooseVersion("1.2"), reason="require pytorch>=1.2"
espnet2/train/test_iterable_dataset.py:    LooseVersion(torch.__version__) < LooseVersion("1.2"), reason="require pytorch>=1.2"
espnet2/train/test_iterable_dataset.py:    LooseVersion(torch.__version__) < LooseVersion("1.2"), reason="require pytorch>=1.2"
espnet2/train/test_iterable_dataset.py:    LooseVersion(torch.__version__) < LooseVersion("1.2"), reason="require pytorch>=1.2"
espnet2/train/test_iterable_dataset.py:    LooseVersion(torch.__version__) < LooseVersion("1.2"), reason="require pytorch>=1.2"
espnet2/train/test_iterable_dataset.py:    LooseVersion(torch.__version__) < LooseVersion("1.2"), reason="require pytorch>=1.2"
espnet2/train/test_iterable_dataset.py:    LooseVersion(torch.__version__) < LooseVersion("1.2"), reason="require pytorch>=1.2"
espnet2/train/test_iterable_dataset.py:    LooseVersion(torch.__version__) < LooseVersion("1.2"), reason="require pytorch>=1.2"
espnet2/train/test_iterable_dataset.py:    LooseVersion(torch.__version__) < LooseVersion("1.2"), reason="require pytorch>=1.2"
espnet2/train/test_iterable_dataset.py:    LooseVersion(torch.__version__) < LooseVersion("1.2"), reason="require pytorch>=1.2"
espnet2/train/test_iterable_dataset.py:    LooseVersion(torch.__version__) < LooseVersion("1.2"), reason="require pytorch>=1.2"
espnet2/bin/test_enh_inference.py:from distutils.version import LooseVersion
espnet2/bin/test_enh_inference.py:is_torch_1_2_plus = LooseVersion(torch.__version__) >= LooseVersion("1.2.0")
espnet2/layers/test_stft.py:from distutils.version import LooseVersion
espnet2/layers/test_stft.py:    LooseVersion(torch.__version__) < LooseVersion("1.3"),
test_loss.py:from distutils.version import LooseVersion
test_loss.py:        if LooseVersion(torch.__version__) < LooseVersion("1.0"):
test_loss.py:    if LooseVersion(torch.__version__) < LooseVersion("1.0"):
test_recog.py:from distutils.version import LooseVersion
test_recog.py:is_torch_1_2_plus = LooseVersion(torch.__version__) >= LooseVersion("1.2.0")

```

**Comment by ShigekiKarita** [comment]
Found pytorch changes in ESPnet
- 1.0.1: torch.distributed.ReduceOp
- 1.1.0: F.cross_entropy(reduction="mean"), torch.repeat_interleave (used in length_regulator), bicubic interporation, torch_complex solve, torch.utils.tensorboard
- 1.2.0: torch.bool (wrong dtype return?), IterableDataset, more optimizers (e.g., AdamW), multi GPU error (is it still alive? I haven't seen them though. https://github.com/pytorch/pytorch/issues/21108)
- 1.3.0: torch.bool (fixed?), more LR schedulers (e.g. CyclicLR), dynamic quantization
- 1.4.0: torch.cuda.max_memory_reserved
- 1.5.0: torch.multiprocessing.spawn.ProcessContext
- 1.6.0: torch.cuda.amp.{autocast, GradScaler}
- 1.7.0: torch.ctc_loss
