### ISSUE TITLE
ESPnet2-TTS development plan

### ISSUE THREAD

**Issue by kan-bayashi** [espnet/espnet#3385]
# TODO

## Models
- [ ] DenoiSpeech
- [ ] Parallel Tacotron2
- [ ] VITS
- [ ] Translatotron2

## Vocoders
- [ ] HiFi-GAN
- [ ] StyleMelGAN

## Recipe
- [x] RUSLAN
  #3378 
  #3390 
- [x] HUI-audio-corpus-german 
  #3375
  #3381
  #3391 
- [x] KKS dataset #3383
- [ ] JTubeSpeech
- [ ] J-MAC
- [ ] J-KAC
- [ ] JMD #3394 
- [ ] AISHELL-3
- [ ] SynPaFlex-Corpus
- [ ] The SIWIS French Speech Synthesis Database
- [ ] CMU INDIC
- [ ] Hi-Fi TTS
- [ ] DiDiSpeech
- [ ] IndicSpeech

## Functions
- [x] Korean G2P #3383
- [x] Runssian G2P #3377
- [x] German G2P #3371
- [x] Spanish G2P #3373
- [x] French G2P #3372
- [ ] Enhanced Japanenes G2P
- [x] Silence trimming at the beginning and the end of audio #3380 
- [ ] Silence trimming at the middle of audio
- [ ] Conversion of MFA alignment to `durations` file
- [ ] Evaluation stage
   - [ ] ASR eval
   - [ ] MOSnet eval
   - [ ] MCD eval

Any suggestions are welcome.

**Comment by Freddy-pp** [comment]
Any plans for Fre-GAN?
https://arxiv.org/abs/2106.02297
https://github.com/rishikksh20/Fre-GAN-pytorch

**Comment by sw005320** [comment]
Quantization?

**Comment by sw005320** [comment]
How about using speech enhancement (to clean the model during training or remove some distortions during inference)?
ESPnet SE has several pre-trained models and will have more models.

**Comment by kan-bayashi** [comment]
> How about using speech enhancement (to clean the model during training or remove some distortions during inference)?
> ESPnet SE has several pre-trained models and will have more models.

That sounds nice. If 24 khz and 22.05 khz settings are available, that is perfect.

**Comment by sw005320** [comment]
@Emrys365, @LiChenda, @shincling, @neillu23, is it possible to build speech enhancement with 24 khz and 22.05 khz?
I think we don't have such pre-trained models for now.

**Comment by Emrys365** [comment]
> @Emrys365, @LiChenda, @shincling, @neillu23, is it possible to build speech enhancement with 24 khz and 22.05 khz?
> I think we don't have such pre-trained models for now.

Maybe we can just train a model on the noisy reverberant speech database (https://github.com/espnet/espnet/pull/3243)? It seems to have a high sampling rate (48 kHz).
