### ISSUE TITLE
ESPnet2-SLU development plan

### ISSUE THREAD

**Issue by siddhu001** [espnet/espnet#3687]
# TODO

- [X] Documentation
  - [X] Readme.md

## New Features
- [X] Task
  - [X] Intent Classification @siddhu001
  - [X] Slot Filling @siddhu001
  - [X] Dialogue Act Classification @akreal
  - [X] Emotion Recognition @YushiUeda 
- [X] ASR Multitasking @siddhu001
- [ ] NLU Multitasking @siddhu001
- [X] Pretrained ASR models as feature extractor @simpleoier 
- [X] Pretrained NLU models as feature extractor @akreal
- [X] Multilingual SLU
  - [X] Tamil @SujaySKumar
  - [X] Sinhala @karthik19967829
  - [X] Japanese @YushiUeda 
  - [X] Dutch @pyf98
- [x] Combine context from previous utterances
  - [x] Dialogue Act Classification @akreal 
  - [ ] Intent Classification @siddhu001
- [x] Support using tasks in pipeline manner @siddhu001
 
## Models
- [X] End to end SLU @siddhu001
- [ ] Pipeline SLU @siddhu001
- [ ] Multi Decoder SLU

## Demos
- [x] General working demo similar to https://huggingface.co/spaces/akhaliq/ESPnet2-TTS @siddhu001
- [x] Supporting tasks in pipeline Google collab demo @siddhu001
- [x] Multilingual SLU Google collab demo @siddhu001

## Recipe
- [x] Fluent Speech Commands Dataset Intent Classification @siddhu001
  - [X] https://github.com/espnet/espnet/pull/3653
  - [x] MASE eval splits @siddhu001
- [X] SLURP @siddhu001
  - [X] Intent Classification https://github.com/espnet/espnet/pull/3674
  - [X] Entity classification
- [X] SNIPS @yuekaizhang 
  - [X] https://github.com/espnet/espnet/pull/3619
- [X] Harper Valley Bank corpus @karthik19967829
  - [X] Intent Classification
  - [X] Dialogue Act Classification
- [X] Grabo @pyf98
  - [X] https://github.com/espnet/espnet/pull/3669
- [X] Google Speech Commands @pyf98
- [X] Japanese dialogue act classification @YushiUeda 
- [ ] Tamil Intent Classification @SujaySKumar
- [X] CATSLU Intent Classification @SujaySKumar
- [X] Sinhala Intent Classification @karthik19967829
- [X] Switch board Dialogue Act Classification @akreal
  - [X] Update with using Hubert ASR
- [X] IEMOCAP Emotion Recognition @YushiUeda

Any suggestions are welcome.
