### ISSUE TITLE
Development plan for ESPnet2 singing voice synthesis

### ISSUE THREAD

**Issue by A-Quarter-Mile** [espnet/espnet#4437]
We are now migrating [Muskit](https://github.com/SJTMusicTeam/Muskits), an open-source music processing toolkit, into ESPnet2.
Muskit focuses on benchmarking the end-to-end singing voice synthesis and expects to extend more tasks in the future. The main structure and base codes are adapted from ESPnet.

We also expect to make some new attempts in combination with the existing tasks (eg. TTS) under ESPnet2. We welcome your suggestions and contributions!

##  Code Merging

- [x] Merge modules from Muskit (mainly under the following two folders)
    - [x] tools/
    - [x] muskit/
 - [ ] Add authorship notes 

##  Networks

- [x] RNN-based non-autoregressive model
- [x] Xiaoice
- [ ] Sequence-to-sequence Transformer (with GLU-based encoder)
- [ ] MLP singer
- [x] Tacotron-singing 
- [ ] DiffSinger 
- [x] VISinger

## Recipes

- [ ] CSD
- [x] Itako
- [x] Kiritan
- [ ] KiSing
- [ ] Multilingual_four
- [ ] NIT_song070
- [ ] No7singing
- [x] Ofuton_p_utagoe_db
- [x] Oniku_kurumi_utagoe_db
- [x] Opencpop
- [x] PJS
- [ ] JSUT
- [ ] Ameboshi_ciphyer_utagoe_db

## Documentation

- [x] Installation 
- [x] Running instructions
- [x] Recipe explanation 
- [ ] pretrained_models 

## New Functions

- [x] Add musicXML in front-end
- [x] Add CI test
- [x] Upload to Huggingface

**Comment by ftshijt** [comment]
Many thanks! Looks very exciting~

**Comment by imiskolee** [comment]
oh, amazing!  did any processing now, which branch for it or not started yet?

**Comment by ftshijt** [comment]
Thanks for your interest in our plan @imiskolee We do not have any open codebases published yet, most codebases are still under private development. Please stay tuned~
