### ISSUE TITLE
Development plan for v.0.3.0

### ISSUE THREAD

**Issue by sw005320** [espnet/espnet#444]
If you have any suggestions for the plan, please let us know.

- [x] modularization #440, #484 
- [x] add travis CI test for `run.sh` and `utils/*` #484
- [x] add test scripts for `utils/*` #498 
- [x] add GRU architectures #496 
- [x] tensorboard support #506 
- [x] batch decoding #318 
- [x] enhance (speech) translation recipes #468 
- new ASR recipe #491 
  - [x] improve the ASR baseline by speed perturbation, small mtlalpha, dropout #480 #491 #521 #546 
  - [x] refine noisy reverberant ASR recipes, adding frontend processing (not end-to-end now) 
  - [x] speech separation recipes #457 
  - [x] including Nara WPE and beamforming (ami, chime4, chime5, reverb) #435  #467 #469 
- [x] use of hdf5 #412 #493 
- [x] use chainer v5.X (now we fix a version at 4.3.1 with @jnishi's patch) #460 
- [x] support pytorch 1.0 #553 
- [x] remove deprecated warning from PyTorch #553 
- [ ] transformer #465 
- [ ] recurrent dropout in decoder
- [ ] use cudnn CTC for chainer and pytorch #433 
- [ ] change the beam search interface #489 
- [x] bug fix etc. #481 #490 #544 
- [ ] config files in addition to the options

**Comment by sw005320** [comment]
I just made a branch for this development plan https://github.com/espnet/espnet/tree/v.0.3.0, as it affects to many people if we work on the master.
Please work on the above items in this branch.

**Comment by sw005320** [comment]
Hi all, HDF5 extension seems to be working and I'm thinking of merging this v.0.3.0 to the master in a month.

I just want to list the ongoing items that I want to include to v.0.3.0
- Transformer: @ShigekiKarita (and @Fhrozen) is working on it, and we could get his PR in a week, and possibly merge it in two weeks
- Beam search interface: again @ShigekiKarita is working on it. This may be only used for the transformer for v.0.3.0, but we can extend to use this for RNN based encoder-decoder in the next update.
- Speech translation: @hirofumi0810 is working on it. Now it produces comparable/superior performance to the other people (Google)'s report. We already reviewed most of parts and we could merge it in a week or so.
- Speech separation and recognition @simpleoier is working on it. The main part is finished, but it may take some time to well merge the v.0.3.0, as it extends several main functions/classes to handle multiple output streams.

@gtache, in this stage, your refactoring work #526 may yield some conflicts with the above items, which will cause some delays, and I want you to consider it after we finish v.0.3.0 (this very good contribution though). Also, some of your ideas in #483 are very good (I'll merge #544 after @kan-bayashi's input). Is that possible for you to work on some of your other action items on top of the current v.0.3.0 branch? I want to incorporate them if it will be finished in a month.

**Comment by hirofumi0810** [comment]
@sw005320 Is it possible to include pure machine translation modules to v.0.3.0?
I'm ready to send a PR and show results on fisher callhome spanish recipe.

**Comment by sw005320** [comment]
This is great. Yes, you could make a directory `egs/XXX/mt1` and include it.

**Comment by sw005320** [comment]
We have several pending items, but I think it's time to make v.0.3.0 to the master branch and we can continue the rest of items (e.g., @gtache's items, @hirofumi0810's MT, @kamo-naoyuki's pytorch 1.0 and @simpleoier's separation). But I still want to include the transformer (prototype is fine), and I want @ShigekiKarita to work on this.

**Comment by sw005320** [comment]
We'll merge v.0.3.0 branch to the master soon as a beta release. I still want to ask some of you to finish new functions (@simpleoier, @ShigekiKarita, @hirofumi0810) for the official release.

**Comment by sw005320** [comment]
I just merged the v.0.3.0 branch to the main branch as a beta version :)
I'd like to thank all (@gtache, @hirofumi0810, @kan-bayashi, @kamo-naoyuki, @ShigekiKarita, @takenori-y, @simpleoier, @Fhrozen, @sas91, @mn5k, @JaejinCho. @Xiaofei-Wang, @jnishi, @Magic-Bubble).

There are still pending issues and we also need to fix bugs to make a stable version.
I really appreciate if you test some recipes with this new version.

We'll also summarize the release note soon.

**Comment by Fhrozen** [comment]
@sw005320, I am rebuilding the docker containers to support v.0.3.0. There are some issues, as the mecab installation (PR done). 
I will recommend to split the mecab label from the Makefile into 2-3 labels > mecab, swig, mecab-python. I just got the problem during the installation of mecab-python3, but the current label erase and rebuild from mecab.
I will continue with the containers once the PR is merged to keep the docker branch in docker issues only.
