### ISSUE TITLE
Development Plan for ESPNet2 -- Unsupervised ASR (EURO)

### ISSUE THREAD

**Issue by DongjiGao** [espnet/espnet#4749]
We have been developing ESPnet2 for the unsupervised speech recognition (UASR) task. The code follows the basic architecture of espnet2

Welcome your requests for these particular directions and contributions! The followings are our development plans.

# Progress & Plan
- [x] A new task for speech recognition
- [x] UASR recipe template
# Network Architectures
- [x] GAN
- [x] k2 WFST decoder
# Documentation
- [ ] add documentation in https://github.com/espnet/espnet/tree/master/doc
- [ ] prepare the webpage to put some demonstration
- [ ] create notebook for the demo
# Recipe
- [ ] LibriSpeech
- [x] TIMIT

**Comment by geoph9** [comment]
Hi, is there any update on the librispeech EURO recipe? I am trying to replicate some of the results of the wav2vec-U and wav2vec-U 2.0 papers and I am having issues doing that using the uasr template recipe.

**Comment by sw005320** [comment]
@ftshijt and @DongjiGao, can you share the current status?

**Comment by ftshijt** [comment]
I believe we do not have wav2vec-U 2.0 supported yet (those we have the implementation, but the performance is as unstable as the one in Fairseq). I do not have other follow-ups to this direction recently.

**Comment by geoph9** [comment]
Ah I see. And just out of curiosity, is there any plan to upload your uasr librispeech recipe (for the initial wav2vec-U paper)?

**Comment by ftshijt** [comment]
Sure thing! @DongjiGao could you help upload your pre-trained models?

**Comment by DongjiGao** [comment]
Sure.


On Jul 22, 2023, at 2:33 PM, Jiatong ***@***.***> wrote:

﻿

Sure thing! @DongjiGao<https://github.com/DongjiGao> could you help upload your pre-trained models?

**Comment by 30stomercury** [comment]
Hi @DongjiGao and @ftshijt, thanks for the efforts! I wanted to follow-up on the librispeech EURO recipe. Any pointers to the recipe would be appreciated. 

Thanks a lot.
