### ISSUE TITLE
Development plan of TTS recipes

### ISSUE THREAD

**Issue by kan-bayashi** [espnet/espnet#561]
@kan-bayashi and @takenori-y plan to improve TTS recipes.
Action items are as follows:
- [x] Add Japanese TTS recipe using JSUT corpus #569 
- [x] Add other language recipes using M-AILABS speech dataset #562 
- [x] Replace libspeech with libriTTS
- [x] Add instant decoding script (generate a wav file  from a given text) #549 #871
- [ ] Integrate neural vocoder
- [ ] Add another types of neural vocoder (FFTNet, WaveGlow, etc...)
- [x] Add Transformer TTS #752
- [x] Add non-autoregressive Transformer TTS (FastSpeech)  #848

If you have another suggestions, please let me know.

**Comment by r9y9** [comment]
I realized that we'd better support tokenization at training time on-the-fly for TTS to implement char/phoneme mixing (can be viewed as data augmentation) as proposed in [DeepVoice3](https://arxiv.org/abs/1710.07654) and [Representation mixing](https://arxiv.org/abs/1811.07240) papers. Showing by code:

```py
In [22]: en.sequence_to_text(en.text_to_sequence("hello world", p=0.5))
Out[22]: 'hello world.~'

In [23]: en.sequence_to_text(en.text_to_sequence("hello world", p=0.5))
Out[23]: '{HH AH0 L OW1} world.~'

In [24]: en.sequence_to_text(en.text_to_sequence("hello world", p=0.5))
Out[24]: 'hello world.~'

In [25]: en.sequence_to_text(en.text_to_sequence("hello world", p=0.5))
Out[25]: 'hello .{W ER1 L D}~'

In [26]: en.text_to_sequence("hello world", p=0.5)
Out[26]: [107, 74, 118, 124, 64, 50, 42, 45, 39, 31, 60, 1]
```

Code looks like this: https://github.com/r9y9/deepvoice3_pytorch/blob/1c75289e47c6c6a5de976e21fc7498266a9bb4b6/deepvoice3_pytorch/frontend/en/__init__.py#L26-L32

I have a working demo locally. I will make a PR once it gets in good shape. 

Besides, I'm trying to make a simpler, kaldi-free TTS recipe combined with my WaveNet vocoder implementation (https://github.com/r9y9/wavenet_vocoder). I believe TTS folks are not necessarily familiar with kaldi tools, its data structure, etc. and current TTS recipes can be simplified by making it kaldi-free. Not yet fully done yet, but I'm going to make a PR for that in the near future.

**Comment by kan-bayashi** [comment]
This is great.
I feel this is needed especially when we use @takenori-y’s synth_wav.sh script.

Current TTS recipe does not use kaldi feature extraction tool except for compute-cmvn-stats but it can be replaced with @kamo-naoyuki ‘s tool.

But I want to keep the data structure because the use of the same structure as in ASR is easy to maintain and allow the use of kaldi’s utility tools.
Also, it can be useful when we make the back translation like training. 
How do you think? @sw005320 @ShigekiKarita

**Comment by r9y9** [comment]
To be clear, I'm not going to break everything in the current TTS recipe and not going to change the data.json format (am I right this is what you mean by the data structure?), but just adding another recipe that is more easily pluggable to the other neural vocoder implementations (well, talking about mine for now). Running a TTS example doesn't require users to know about the kaldi and espnet data structure, however, if one wants to extend it as I mention in #876  (e.g., plugging it with their own vocoder implementation, etc), it requires some knowledge like  ark, scp format, utility tools, format of data.json, how they are used, etc. 

By kaldi-free, I mean 1) no use of kaldi bin tools 2) no use of kaldi utility tools 2) no knowledge required about kaldi data structure to plug with external neural vocoder implementation (as most of the popular neural vocoders doesn't use ark/scp format, but just use numpy arrays as far as I know).  I'm not saying kaldi tools are not useful, but just I want to try to make a kaldi-decoupled simpler recipe, which doesn't require users to know much about kaldi for extending a recipe. I may change my mind in future though, for now I'm thinking of simply replacing the use of ark format to the numpy array, while keeping data.json format as same as the current one. https://github.com/espnet/espnet/blob/fcf4c8ceeb413cea333ed98dc6c9fb5339bf1150/espnet/utils/io_utils.py#L372

> But I want to keep the data structure because the use of the same structure as in ASR is easy to maintain and allow the use of kaldi’s utility tools.

I understand the point, but I'm not sure if the utility tools are really beneficial at a cost of adding kaldi dependency.

**Comment by kan-bayashi** [comment]
In my understanding, `kaldi-free` means no use of compiled kaldi tools, but keep the kaldi fundamental data structure.
The structure I mean is that kaldi fundamental files:
```
data/
    - wav.scp
    - (segments)
    - text
    - utt2spk
    - spk2utt
```
I think a problem of kaldi dependecy is a heavy compile. 
If we use only kaldi shell utilities, we do not need to compile, what we need is just clone kaldi.
By using this structure and shell utils, we can easy combine recipes, check the file correctness, convert file format without dump thanks to command pipe, etc... 
(And thanks to a great tool [kaldiio](https://github.com/nttcslab-sp/kaldiio), we can deal with these files within python).
So I want to keep this structure. 
Any feature file format is ok. e.g. `ark` or `hdf5` or `npy`. (PersonallyI like hdf5).

Due to the memory consumption issue, we consider to change the format of `data.json`.
https://github.com/espnet/espnet/issues/533

**Comment by kan-bayashi** [comment]
Sorry for my conservative option :(
Maybe I can change my mind if you show some examples.

**Comment by r9y9** [comment]
It’s totally okay and thank you for your comments! I’m still at thinking the best way. I’ll show an example once it’s ready.

**Comment by sw005320** [comment]
Sorry for my late response. I also want to see an example. I think we could find a nice solution for Kaldi-free but both Kaldi-like and generic pythonic styles can co-exist.

**Comment by kan-bayashi** [comment]
Continue on #977
