### ISSUE TITLE
Development plan for 0.5.0

### ISSUE THREAD

**Issue by ShigekiKarita** [espnet/espnet#849]
This issue is derived from 0.4.0 #650. Feel free to add or remove items.

- general functions
  - [x] measure coverage #850 
  - [ ] achieve 80% test coverage
  - [ ] asynchronous snapshot saving
  - [ ] completely fix pytorch warp_ctc
- new functions
  - [x] neural machine translation #563
  - [ ] transformer LM
  - [ ] RNN transducer 
  - [ ] cycle consisntency based semi-supervised training #712 
  - [ ] add neural vocder
  - [x] FastSpeech #848
- demo related
  - [ ] online decoding #638 #645 
  - [ ] speed up for decoding #748 #980 
  - [ ] Kaldi-free
  - [ ] tutorial based on [Google colab](https://colab.research.google.com/notebooks/welcome.ipynb) #1003 
- new recipes (see https://github.com/espnet/espnet/wiki/How-to-port-the-Kaldi-recipe-to-the-ESPnet-recipe%3F when you port the Kaldi recipe to the ESPnet recipe)
    - [ ] icsi meeting (https://github.com/kaldi-asr/kaldi/pull/2435)
    - [x] jsut ASR #793 
    - [ ] common voice #1000 
- update major recipes with SOTA for several ASR benchmarks
    - [ ] SWB
    - [ ] WSJ
    - [x] Librispeech #970 
- update multi channel recipes
    - [ ] AMI #819 
    - [ ] CHiME4  #837 
- documentation
    - [ ] we should add more contents (see #876)...
    - [x] clarify the version policy #contributing
    - [ ] publish each version release with Zenodo (https://zenodo.org/)

**Comment by tomotious** [comment]
I am looking forward to the development of RNN transducer

**Comment by b-flo** [comment]
Hi @tomotious ,

 RNN Transducer (vanilla & attention) is close to completion. We are doing validation on some datasets and we will push it into ESPNET soon.
