### ISSUE TITLE
Development plan of TTS recipes for v.0.5.0

### ISSUE THREAD

**Issue by kan-bayashi** [espnet/espnet#977]
Continue from #561 

- [x] Integrate neural vocoder #1081
- [ ] GPU batch inference
- [x] Multi-speaker Transformer #1001
- [x] Multi-speaker FastSpeech #1006 
- [x] Add Transformer recipe 
    - [x] JSUT #1009 
    - [x] LibriTTS #1005 
- [x] Add Chinese recipe #1259
- [ ] Re-design interface to be compatible with other types of embeddings
- [ ] Integrate online text cleaning in training #998 

If you have other suggestions, please let me know.

**Comment by Pydataman** [comment]
@kan-bayashi can you add transformer recipe for chinese corpus？

**Comment by kan-bayashi** [comment]
@Pydataman Thank you for your suggestions!
I added it to action items.
BTW, I'm not familiar with Chinese TTS corpus.
So if you know the nice free corpus for Chinese TTS, please let me know.

**Comment by Pydataman** [comment]
@kan-bayashi 
ok
but I don't know how much data is in chinese, I have tts data for two people here, about 6 hours for each person. for traning tts, these data may be a bit less. In chinese tts, I can help and participate in this project. thanks

**Comment by lingjzhu** [comment]
Hello, I was wondering if this post is still relevant. But I know that there is a 12-hour Chinese TTS corpus. It can be found at this website:https://www.data-baker.com/open_source.html. The download link is at the end of the page.

**Comment by kan-bayashi** [comment]
@lingjzhu Sorry for late reply. Thank you for sharing information.
I made the recipe using this dataset #1259

**Comment by kan-bayashi** [comment]
@lingjzhu That's great.
But we need to care about the hyperparameters of feature extraction.
Could you check the setting is the same?
https://github.com/espnet/espnet/blob/257d7cd14d47eff8846ed9db45b21a1c403f6d20/egs/csmsc/tts1/run.sh

**Comment by lingjzhu** [comment]
I use the default setting of 16bit MOK in r9y9's repo. Here are the detailed parameters. 
Unfortunately some parameters are differents, including sampling rate and fmin. 
  "sample_rate": 22050,
  "num_mels": 80,
  "fmin": 125,
  "fmax": 7600,
  "fft_size": 1024,
  "hop_size": 256,
  "frame_shift_ms": null,
  "win_length": 1024,
  "win_length_ms": -1.0,
  "window": "hann",
  "highpass_cutoff": 70.0,

Are those hyperparameters in your post are used in actual training? If it is going to be helpful, I can also fine-tune the pre-trained WaveNet model using your hyperparameters, which should be fast to complete (in less than three days).   

Just curious, are there any motivation to use the sampling rate of 24000 rather than the more common 22050?

**Comment by r9y9** [comment]
Hi, thank you for using my repository! It would be really helpful if you could share us your trained model! 

As you can see, some of the speech processing parameters are different between us and we will need to fix it if we want to combine our models. How about using fs=24000, n_shift=300, win_length=1200, n_fft=2048, fmin=80 (fmin quite depends on the dataset, but 80 sounds okay for me) for both E2E and WaveNet?

I know n_shift=256 and n_fft=1024 works quite well for 22.5kHz audio, but the above-mentioned parameters are well-used in recent E2E TTS research (e.g., https://arxiv.org/abs/1712.05884).

I don't think 22.5kHz is common in TTS community... Personally I never use it except for LJSpeech. For the reference, LibriTTS provides audio with 24kHz sampling rate.

**Comment by lingjzhu** [comment]
OK. Thanks for your reply. I use Nvidia's TTS and WaveGlow and found 22050 worked well with this dataset. But as you said, I think we should use consistent hyperparameters. I will change the hyperparamers and retrain the model.

**Comment by lingjzhu** [comment]
@r9y9 Just to confirm, do you think the following hyperparameters work? If yes, I will retrain the model today.

{
  "name": "wavenet_vocoder",
  "input_type": "raw",
  "quantize_channels": 65536,
  "preprocess": "preemphasis",
  "postprocess": "inv_preemphasis",
  "global_gain_scale": 0.55,
  "sample_rate": 24000,
  "silence_threshold": 2,
  "num_mels": 80,
  "fmin": 80,
  "fmax": 7600,
  "fft_size": 2048,
  "hop_size": 300,
  "frame_shift_ms": null,
  "win_length": 1200,
  "win_length_ms": -1.0,
  "window": "hann",
  "highpass_cutoff": 70.0,
}

**Comment by kan-bayashi** [comment]
About sampling rate, the original sampling rate is 48kHz, so I use 24 kHz (integer multiple downsampling is better).

**Comment by r9y9** [comment]
> "global_gain_scale": 0.55,

This is highly depending on the dataset you are working on. You need to turn the parameter so that clipping never happens.

Other parameters look good for me.

**Comment by lingjzhu** [comment]
Thanks. I will share the model in a few days.

**Comment by r9y9** [comment]
FYI, pre-emphasis changes the gain of signals and that's why we need to tweak the global gain scaling parameter. If you want to know why we apply preemphasis on waveform as a preprocessing, please see LPCNet paper: https://jmvalin.ca/papers/lpcnet_icassp2019.pdf. In short, pre-emphasis has similar effects to noise shaping and reduces noise greatly at inference time.

**Comment by lingjzhu** [comment]
Thanks! I am training the model now. After Stage 0 was completed,  numbers around 1.12 was suggested as the global scaling factor. So I set it to 1.10.

Could you please share some mel spectrograms predicted by your TTS models so that I can evaluate the WaveNet? Thanks.

**Comment by kan-bayashi** [comment]
@lingjzhu Now I'm training the model.
Once finished, I will upload samples, models, and features!

**Comment by kan-bayashi** [comment]
Hi @lingjzhu.
I finished the training of initial transformer.
You can download generated features.
https://drive.google.com/open?id=14LZZPPRCkmonMJbjOjfTZ7x8JaHDRMM2

**Comment by lingjzhu** [comment]
@kan-bayashi Hi, I have tested the WaveNet vocoder on the generated features. Here are some samples. They sound pretty good. 
[samples.zip](https://github.com/espnet/espnet/files/3725509/samples.zip)

**Comment by kan-bayashi** [comment]
@lingjzhu Cooool!
Could you upload your Wavenet model?

**Comment by lingjzhu** [comment]
Sure. I haven't finished training yet. The model I used was trained for 500k iterations but there are still some noises. I will upload the model once the training is completed.

**Comment by lingjzhu** [comment]
The model can be found at this link: https://drive.google.com/file/d/1qhfz1Kmj46hFByTN6m7Vgis2bxuaeLR_/view?usp=sharing

Here are samples for these two models. The sample generated by the "ema" model still contan some artifacts.
[009997_600k.zip](https://github.com/espnet/espnet/files/3726823/009997_600k.zip)

**Comment by WhiteFu** [comment]
> OK. Thanks for your reply. I use Nvidia's TTS and WaveGlow and found 22050 worked well with this dataset. But as you said, I think we should use consistent hyperparameters. I will change the hyperparamers and retrain the model.

@lingjzhu  Are you using pretrain WaveGlow model from Nvidia?  Or training a new WaveGlow model by your Chinese corpus?  Can you improve some samples? I have been doing similar work recently.

**Comment by lingjzhu** [comment]
@WhiteFu Please refer to this post for details and samples.
https://github.com/NVIDIA/waveglow/issues/132

**Comment by WhiteFu** [comment]
@lingjzhu Thank you very much!

**Comment by lingjzhu** [comment]
@kan-bayashi I have finished training the WaveNet for 1000k steps. 
They are available at:https://drive.google.com/file/d/1MQ562lpuDgYKozOP1Jv_gpsfmfLv1ax4/view?usp=sharing

Here is the configuration file. 
[hparams.zip](https://github.com/espnet/espnet/files/3740974/hparams.zip)

Here are the audio samples of the Tacotron2 predicted mel spectrograms. There no substantial improvement compared to the 600k model.
[009997_100k.zip](https://github.com/espnet/espnet/files/3741002/009997_100k.zip)

**Comment by WhiteFu** [comment]
> @kan-bayashi I have finished training the WaveNet for 1000k steps.
> They are available at:https://drive.google.com/file/d/1MQ562lpuDgYKozOP1Jv_gpsfmfLv1ax4/view?usp=sharing
> 
> Here is the configuration file.
> [hparams.zip](https://github.com/espnet/espnet/files/3740974/hparams.zip)
> 
> Here are the audio samples of the Tacotron2 predicted mel spectrograms. There is no substantial improvement compared to the 600k models.
> [009997_100k.zip](https://github.com/espnet/espnet/files/3741002/009997_100k.zip)

@lingjzhu  The audio quality is very good! Is your tacotron2’s configuration refer to espnet or Nvidia? Can you provide details about the audio preprocessing?

**Comment by lingjzhu** [comment]
@WhiteFu The Tacotron2 predictions are those provdied by @kan-bayashi in this post. I used the same processing step as the Espnet recipe to train the WaveNet. All hyperparamers are specified in the hparams.zip. You'll need to look at r9y9's WaveNet vocoder to see how processing is carried out.

**Comment by WhiteFu** [comment]
@lingjzhu Thank you for your patience, Effectively solved my confusion. 
@kan-bayashi @r9y9 Thank you for providing such a wonderful repo!

**Comment by kan-bayashi** [comment]
@lingjzhu Thank you for your sharing!
I will add the model as pretrained model of this repo!

**Comment by kan-bayashi** [comment]
@WhiteFu Note that the features are generated by our Transformer not Tacotron2.
(But the quality itself is almost the same among them)

**Comment by geekboood** [comment]
@lingjzhu Hi, I wonder how long does wavenet take to synthesize a piece of sound? The matrix shape I get from Transformer model is (472, 80) and I see the hop_size in your configuration is 300. As a result, it takes me 140400 steps to synthesize a piece of sound which need about one hour.

**Comment by lingjzhu** [comment]
@geekboood Yes, WaveNet is very slow. In my case, it took 15 mins to generate a 6-second sentence on a 2080Ti. But one hour seems too long to me. Are you using a GPU? You can also try to synthesize multiple sentences together to speed up the synthesis speed.

**Comment by r9y9** [comment]
It depends, but it wouldn't be too slow if we increase the batch size. I usually use 64 or larger.

**Comment by dhgrs** [comment]
I agree with that WaveNet is slow. And I know two solutions. One is to use [nv-wavenet](https://github.com/NVIDIA/nv-wavenet). But it has some problems. Supported hardware is limited, network size is limited, MoL is not supported and so on. The other one is to use other neural vocoder which is faster than WaveNet. Like [WaveGlow](https://github.com/NVIDIA/waveglow), [LPCNet](https://github.com/mozilla/LPCNet) or something else. But supporting other vocoder is maybe big change for espnet. So I think that we need to be carefully to support or not.

**Comment by kan-bayashi** [comment]
Now I'm constructing Parallel WaveGAN as real-time neural vocoder.
Please look forward to it!
https://github.com/kan-bayashi/ParallelWaveGAN

**Comment by kan-bayashi** [comment]
I will make new issue for v.0.6.0.
Close this issue.
